//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICATION_PERMISISONS
    {
        public int APP_PERMISSION_ID { get; set; }
        public int APP_ID { get; set; }
        public int EMPLOYEE_ID { get; set; }
        public string APP_PERMISISON_ALLOWED { get; set; }
        public string APP_PERMISSION_MAX_SESSION { get; set; }
        public string APP_PERMISSION_DESCRIPTION { get; set; }
    
        public virtual APPLICATIONS APPLICATIONS { get; set; }
        public virtual EMPLOYEES EMPLOYEES { get; set; }
    }
}
