//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UTL_AAEntities2 : DbContext
    {
        public UTL_AAEntities2()
            : base("name=UTL_AAEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APPLICATION_MENUS> APPLICATION_MENUS { get; set; }
        public virtual DbSet<APPLICATION_PERMISISONS> APPLICATION_PERMISISONS { get; set; }
        public virtual DbSet<APPLICATIONS> APPLICATIONS { get; set; }
        public virtual DbSet<EMPLOYEE_DENIED_PERMISSION> EMPLOYEE_DENIED_PERMISSION { get; set; }
        public virtual DbSet<EMPLOYEES> EMPLOYEES { get; set; }
        public virtual DbSet<PERMISSIONS> PERMISSIONS { get; set; }
        public virtual DbSet<ROLE> ROLE { get; set; }
        public virtual DbSet<ROLE_PERMISSION_ALLOWED> ROLE_PERMISSION_ALLOWED { get; set; }
        public virtual DbSet<USER_ROLES> USER_ROLES { get; set; }
    }
}
