//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE_DENIED_PERMISSION
    {
        public int DENIED_ID { get; set; }
        public int EMPLOYEE_ID { get; set; }
        public int MENU_ID { get; set; }
        public string PERMISSION_CODE { get; set; }
        public string DENIED_PERMISSION_DENIED { get; set; }
    
        public virtual APPLICATION_MENUS APPLICATION_MENUS { get; set; }
        public virtual EMPLOYEES EMPLOYEES { get; set; }
    }
}
