//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE_PERMISSION_ALLOWED
    {
        public int ROLE_PERMISSION_ID { get; set; }
        public int ROLE_ID { get; set; }
        public int MENU_ID { get; set; }
        public string GRANT_PERMISSION { get; set; }
        public string VIEW_PERMISSION { get; set; }
        public string INSERT_PERMISSION { get; set; }
        public string UPDATE_PERMISSION { get; set; }
        public string DELETE_PERMISSION { get; set; }
    
        public virtual APPLICATION_MENUS APPLICATION_MENUS { get; set; }
        public virtual ROLE ROLE { get; set; }
    }
}
