//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEES()
        {
            this.APPLICATION_PERMISISONS = new HashSet<APPLICATION_PERMISISONS>();
            this.EMPLOYEE_DENIED_PERMISSION = new HashSet<EMPLOYEE_DENIED_PERMISSION>();
            this.USER_ROLES = new HashSet<USER_ROLES>();
        }
    
        public int EMPLOYEE_ID { get; set; }
        public string EMPLOYEE_FIRST_NAME { get; set; }
        public string EMPLOYEE_LAST_NAME { get; set; }
        public string EMPLOYEE_DISPLAY_NAME { get; set; }
        public string EMPLOYEE_STATUS { get; set; }
        public string EMPLOYEE_DEPARTMENT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPLICATION_PERMISISONS> APPLICATION_PERMISISONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE_DENIED_PERMISSION> EMPLOYEE_DENIED_PERMISSION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_ROLES> USER_ROLES { get; set; }
    }
}
