//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_ROLES
    {
        public int USER_ROLE_ID { get; set; }
        public int EMPLOYEE_ID { get; set; }
        public int ROLE_ID { get; set; }
        public string USER_ROLE_ALLOWED { get; set; }
    
        public virtual EMPLOYEES EMPLOYEES { get; set; }
        public virtual ROLE ROLE { get; set; }
    }
}
